### ISSUE TITLE
Missing Phoenix Wallet

### ISSUE THREAD

**Issue by bitcoin-eagle** [lightsats/lightsats#156]
I have an issue. The Phoenix wallet is missing from the list of wallets. Please add it, thanks!

**Comment by rolznz** [comment]
Hi @bitcoin-eagle we have added Phoenix, but it is a non-custodial wallet which requires a minimum balance in order to create channels. We've set a minimum tip size of 10,000 sats for the Phoenix wallet to be included.

![image](https://user-images.githubusercontent.com/33993199/231713715-ebb985e5-db7a-41c1-acab-99beaf1a08bd.png)

**Comment by rolznz** [comment]
This isn't very visible to tippers unless you open the advanced settings. I'll see if we can improve the form to show this

**Comment by rolznz** [comment]
I have added a warning in the tip form:

![image](https://user-images.githubusercontent.com/33993199/235341724-73d2abba-2bf7-41b0-aba1-2f96c2a0d8a8.png)
